# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flatblock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="don't delete it", max_length=30)),
                ('content', models.TextField(help_text='p is paragraph tag, h2 is title tag, u can use it if you want')),
            ],
            options={
                'db_table': 'Flatblocks',
            },
        ),
    ]
