# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticArticles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatblock',
            name='title',
            field=models.CharField(help_text="don't delete it", max_length=50),
        ),
    ]
