# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20160224_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.CharField(choices=[('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020')], default=2016, max_length=10),
        ),
    ]
