# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20160224_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=60, verbose_name='album title'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='discription',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(help_text='Photos in one album must have equal size!', upload_to='images', verbose_name='photo title'),
        ),
    ]
