# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20160224_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='discription',
        ),
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, help_text="it isn't necessary!"),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=60, verbose_name='album title'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(help_text='Photos in one album must have equal size!', upload_to='images', verbose_name='photo title'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
