# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 07:51
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20160321_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('cover', '437x246', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
