# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 08:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_album_cropping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='cropping',
        ),
    ]
