# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_remove_album_cropping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='discription',
        ),
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, help_text="it isn't necessary!"),
        ),
    ]
