# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('when', models.DateTimeField(verbose_name='date of event')),
                ('image', models.ImageField(upload_to='images')),
                ('short_discription', models.CharField(max_length=50)),
                ('full_discription', models.TextField()),
            ],
            options={
                'ordering': ['when'],
                'db_table': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='images')),
                ('short_discription', models.TextField()),
                ('full_discription', models.TextField()),
                ('type', models.CharField(choices=[(1, 'workshop'), (2, 'helpful article')], max_length=10)),
                ('attach', models.FileField(upload_to='materials')),
            ],
            options={
                'db_table': 'Materials',
            },
        ),
    ]
