# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='image',
        ),
        migrations.RemoveField(
            model_name='material',
            name='type',
        ),
        migrations.AlterField(
            model_name='material',
            name='full_discription',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='short_discription',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
