# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 05:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_auto_20160321_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='images')),
            ],
            options={
                'ordering': ['timestamp'],
                'db_table': 'Workshops',
                'verbose_name_plural': 'Workshops',
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='full_discription',
        ),
        migrations.RemoveField(
            model_name='event',
            name='short_discription',
        ),
        migrations.RemoveField(
            model_name='material',
            name='full_discription',
        ),
        migrations.RemoveField(
            model_name='material',
            name='short_discription',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default=datetime.datetime(2016, 4, 16, 5, 49, 45, 25717, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='material',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='material',
            name='attach',
            field=models.FileField(upload_to='files'),
        ),
    ]
