# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_auto_20160321_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='attach',
            field=models.FileField(upload_to='files'),
        ),
    ]
