# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_auto_20160413_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='discription',
            new_name='description',
        ),
    ]
