# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_material_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
            ],
            options={
                'ordering': ['timestamp'],
                'db_table': 'Workshops',
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='full_discription',
        ),
        migrations.RemoveField(
            model_name='event',
            name='short_discription',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
