# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_auto_20160415_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
