# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0010_auto_20160415_1211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workshops',
            options={'ordering': ['timestamp'], 'verbose_name_plural': 'Workshops'},
        ),
    ]
