# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0011_auto_20160415_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshops',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
