# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 22:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visits',
            options={'verbose_name': 'Visit', 'verbose_name_plural': 'Main page visits'},
        ),
    ]
