# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160322_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
