# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('time_in_society', models.CharField(max_length=20)),
                ('courses', models.CharField(max_length=200)),
                ('current_occupation', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Photo must be round or square! You can can make photo round at cutmypic.com', upload_to='images')),
            ],
            options={
                'db_table': 'Alumni',
                'verbose_name_plural': 'Alumnies',
            },
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TextField(help_text='format: 2012-2013', verbose_name='years')),
            ],
            options={
                'db_table': 'Committee',
            },
        ),
        migrations.CreateModel(
            name='CommitteeMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, help_text='Photo must be round or square! You can can make photo round at cutmypic.com', upload_to='images')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Committee')),
            ],
            options={
                'db_table': 'Stuff',
                'verbose_name': 'Member',
                'verbose_name_plural': 'Committee members',
            },
        ),
    ]
