# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.URLField()),
                ('linkedin', models.URLField()),
                ('time_in_society', models.DurationField()),
                ('courses', models.TextField()),
                ('current_occupation', models.TextField()),
                ('current_company', models.TextField()),
            ],
            options={
                'db_table': 'Alumni',
                'verbose_name_plural': 'Alumnies',
            },
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TextField(verbose_name='years')),
                ('image', models.ImageField(upload_to='images')),
            ],
            options={
                'db_table': 'Committee',
            },
        ),
        migrations.CreateModel(
            name='Committee_stuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
                ('discription', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Committee')),
            ],
            options={
                'db_table': 'Stuff',
                'verbose_name': 'member',
                'verbose_name_plural': 'Current stuff',
            },
        ),
    ]
