# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, help_text='Photo must be round or square! You can can make photo round at cutmypic.com', upload_to='images')),
            ],
            options={
                'db_table': 'Stuff',
                'verbose_name': 'member',
                'verbose_name_plural': 'Committee members',
            },
        ),
        migrations.RemoveField(
            model_name='committee_stuff',
            name='committee',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='current_company',
        ),
        migrations.RemoveField(
            model_name='committee',
            name='image',
        ),
        migrations.AddField(
            model_name='alumni',
            name='image',
            field=models.ImageField(blank=True, help_text='Photo must be round or square! You can can make photo round at cutmypic.com', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='courses',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='current_occupation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='time_in_society',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='committee',
            name='time',
            field=models.TextField(help_text='format: 2012-2013', verbose_name='years'),
        ),
        migrations.DeleteModel(
            name='Committee_stuff',
        ),
        migrations.AddField(
            model_name='committeemembers',
            name='committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Committee'),
        ),
    ]
