# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_remove_alumni_current_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='committee_stuff',
            options={'verbose_name': 'member', 'verbose_name_plural': 'Stuff'},
        ),
        migrations.AlterField(
            model_name='committee',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='time',
            field=models.TextField(help_text='format: 2012-2013', verbose_name='years'),
        ),
    ]
