# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20160321_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='current_occupation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='committee_stuff',
            name='discription',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='committee_stuff',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='committee_stuff',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='committee_stuff',
            name='position',
            field=models.CharField(max_length=50),
        ),
    ]
