# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_auto_20160322_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
