# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_auto_20160403_0836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='committee_stuff',
            options={'verbose_name': 'member', 'verbose_name_plural': 'Committee members'},
        ),
    ]
