# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_auto_20160410_0751'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Committee_stuff',
            new_name='CommitteeMembers',
        ),
    ]
