# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_auto_20160415_0700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='committeemembers',
            old_name='discription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='committeemembers',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
